# Generated by Django 5.0.6 on 2026-08-11 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messagethread_agents'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sent_at',
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='in_app', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_due', 'Payment Due'), ('payment_confirmed', 'Payment Confirmed'), ('stage_complete', 'Stage Complete'), ('stage_started', 'Stage Started'), ('message_received', 'Message Received'), ('media_uploaded', 'Media Uploaded'), ('media_expiring', 'Media Expiring'), ('inspection_window', 'Inspection Window Open')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project'),
        ),
    ]
