# Generated by Django 5.0.6 on 2026-08-05 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('staff', '0001_initial'),
        ('stages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('delivery', 'Delivery Footage')], default='photo', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='project-media/')),
                ('blob_name', models.CharField(blank=True, max_length=500)),
                ('blob_url', models.URLField(blank=True)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Video duration', null=True)),
                ('storage_tier', models.CharField(choices=[('hot', 'Hot'), ('cool', 'Cool'), ('archive', 'Archive'), ('deleted', 'Deleted')], default='hot', max_length=10)),
                ('tier_updated_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('client_notified_deletion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footage', to='staff.deliverylog')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='projects.project')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='stages.stage')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Media',
                'verbose_name_plural': 'Project Media',
                'db_table': 'project_media',
                'ordering': ['-created_at'],
            },
        ),
    ]
